name = "FactorMixtures"
uuid = "eb620e83-c205-4263-a9e1-d2a4a5e6f514"
authors = ["john-c-davey <john.c.m.davey@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
